#theme: jekyll-theme-cayman
name: Deepti Korwar, Technical Writer
markdown: kramdown

kramdown:
  auto_ids: true
  parse_block_html: true

#url: https://deeptikorwar.com
permalink: /blog/:year/:month/:day/:title #to include /blog in blog url
