#theme: jekyll-theme-cayman
name: Deepti Korwar, Technical Writer
markdown: kramdown

kramdown:
  auto_ids: true

#url: https://deeptikorwar.com
permalink: /blog/:year/:month/:day/:title #to include /blog in blog url

paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

#Google codes
google_ad_client: ca-pub-2001196324705173 #to turn off ads, remove this value

# jekyll-seo-tag plugin setup 
title: Deepti Korwar
tagline: blog with recipes, short stories and information for technical writers.
description: blog with recipes, short stories and information for technical writers. 
# url: revisit this later
author: Deepti Korwar
logo: https://deeptikorwar.github.io/images/icons/favicon-32x32.png
# google_site_verification: revisit this later
social:
  name: Deepti Korwar
  links:
    - https://twitter.com/DeeptiKorwar
    - https://www.linkedin.com/in/deepti-korwar-06247016
    - https://github.com/deeptikorwar
